### PR TITLE
chore(deps): bump molecule from 0.3.1 to 0.4.1

### PR DESCRIPTION
**Pull request by yangby-cryptape**
- Split the schema file into two files and remove the useless one.
- Add C APIs to build molecule structures.

### CODE REVIEW

**Comment by xxuejie** [comment]
Out of curiosity, do we have a comparison on the generated binary size before and after this change?

**Comment by yangby-cryptape** [comment]
> Out of curiosity, do we have a comparison on the generated binary size before and after this change?

Before:
```diff
rwxr-xr-x 1 root root    7288 Oct 12 01:09 dao
rwxr-xr-x 1 root root   49176 Oct 12 01:09 secp256k1_blake160_sighash_all
rw-r--r-- 1 root root 1048576 Oct 12 01:09 secp256k1_data
rwxr-xr-x 1 root root   56128 Oct 12 01:09 secp256k1_ripemd160_sha256_sighash_all
```

After:
```diff
+rwxr-xr-x 1 root root    7040 Oct 12 01:04 dao
-rwxr-xr-x 1 root root   52248 Oct 12 01:04 secp256k1_blake160_sighash_all
rw-r--r-- 1 root root 1048576 Oct 12 01:04 secp256k1_data
-rwxr-xr-x 1 root root   60224 Oct 12 01:04 secp256k1_ripemd160_sha256_sighash_all
```

Reason:

- Do verify **completely** before parse fields.
  The previous version only check the field which is parsed.

**Comment by xxuejie** [comment]
Thanks! In thise case I'm not particularly worried about the increased bytes, but any thought why the size of dao contract actually decreases, which is different from the other 2?

**Comment by yangby-cryptape** [comment]
> Thanks! In thise case I'm not particularly worried about the increased bytes, but any thought why the size of dao contract actually decreases, which is different from the other 2?

### Check only one time

In previous version, each time to call `mol_cut` will do few checks, but in this version, all checks have be done in `MolReader_Xxxx_verify`, all `getters` will not do any checks.

### The parse function is more simple

The previous version, I provide only one function `mol_cut` to parse data.
So, that function has to pass an argument to parse the type of the data.

```c
parent_type = va_arg(args, mol_type_t);
switch (parent_type) {
    case MolOption: { ... }
    case MolUnion: { ... }
    ... ...
}
```

Now, the compiler generate more c code (lines: 167-> 1731, and a lot of structs is removed), so the API can do it more precise.

```c
#define         MolReader_RawHeader_verify(s, c)                mol_verify_fixed_size(s, 192)                                                                                                                                                                                                                                  
#define         MolReader_RawHeader_get_version(s)              mol_slice_by_offset(s, 0, 4)
#define         MolReader_RawHeader_get_compact_target(s)       mol_slice_by_offset(s, 4, 4)
#define         MolReader_RawHeader_get_timestamp(s)            mol_slice_by_offset(s, 8, 8)
#define         MolReader_RawHeader_get_number(s)               mol_slice_by_offset(s, 16, 8)
#define         MolReader_RawHeader_get_epoch(s)                mol_slice_by_offset(s, 24, 8)
#define         MolReader_RawHeader_get_parent_hash(s)          mol_slice_by_offset(s, 32, 32)
#define         MolReader_RawHeader_get_transactions_root(s)    mol_slice_by_offset(s, 64, 32)
#define         MolReader_RawHeader_get_proposals_hash(s)       mol_slice_by_offset(s, 96, 32)
#define         MolReader_RawHeader_get_uncles_hash(s)          mol_slice_by_offset(s, 128, 32)
#define         MolReader_RawHeader_get_dao(s)                  mol_slice_by_offset(s, 160, 32)

mol_seg_t mol_slice_by_offset(const mol_seg_t *input, mol_num_t offset, mol_num_t size) {                                                                                                                                                                                                                                      
    mol_seg_t seg;                                                              
    seg.ptr = input->ptr + offset;                                              
    seg.size = size;                                                            
    return seg;                                                                 
}    
```

**Pull request merged**
