### PR TITLE
fix: rare failing case in multisig

### PR DESCRIPTION
**Pull request by XuJiandong**
Update docco to 0.9.1

### CODE REVIEW

**Review by quake — APPROVED** [review]

**Comment by XuJiandong** [comment]
deployed on testnet:
```json
{
      "name": "multisig",
      "tx_hash": "0xe6774580c98c8b15799c628f539ed5722f3bc2b17206c2280e15f99be3c1ad71",
      "index": 0,
      "occupied_capacity": 5255000000000,
      "data_hash": "0x50c8623ef5112510ccdf2d8e480d02d0de7288eb9968f8b019817340c3991145",
      "type_id": "0x765b3ed6ae264b335d07e73ac332bf2c0f38f8d3340ed521cb447b4c42dd5f09"
    }
```

**Comment by XuJiandong** [comment]
deployed on mainnet:
```json
{
  "cell_recipes": [
    {
      "name": "multisig",
      "tx_hash": "0x0a13d8d9c83c3374196ee43d4f0116dac497b0fec3e71c04f7cb7780abc455d8",
      "index": 0,
      "occupied_capacity": 5255000000000,
      "data_hash": "0x50c8623ef5112510ccdf2d8e480d02d0de7288eb9968f8b019817340c3991145",
      "type_id": "0xd1a9f877aed3f5e07cb9c52b61ab96d06f250ae6883cc7f0a2423db0976fc821"
    }
  ],
  "dep_group_recipes": []
}
```

**Review by xxuejie — APPROVED** [review]

**Comment by mohanson** [comment]
deployed on testnet via dep_group ( contains secp256k1 precompute table):

{
      "name": "multisig",
      "tx_hash": "0xf2013f123b2cb745e3fdf5c935a3925647496f88090503eef58332a9245b4172",
      "index": 0,
      "data_hash": "0x65a84372e75d18f8f09e9471e2498014ca56a432ff0a500ac13391aadc06bd07",
      "occupied_capacity": 13700000000
}

**Comment by mohanson** [comment]
deployed on mainnet via dep_group ( contains secp256k1 precompute table):

{
      "name": "multisig",
      "tx_hash": "0x44be4f4feda80c0e41783ab10e191df3b2bb5c3731b0970c916dbec385dcdc60",
      "index": 0,
      "data_hash": "0xcca22a9ec6932f6ce45d1ffea621d1f689c0e22ab883db032df1a388a5fa092c",
      "occupied_capacity": 13700000000
}

**Pull request merged**
